language: node_js
node_js:
  - "stable"

before_install:
  - stty cols 80

dist: bionic
sudo: required

addons:
  firefox: latest
  chrome: stable

services:
  - xvfb

before_script:
  - fluxbox >/dev/null 2>&1 &
  - sleep 3

script: npm run build

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  keep_history: false
  local_dir: dist
  on:
    branch: master
